# Generated by Django 3.2.5 on 2021-08-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='num_waiting',
            field=models.IntegerField(default=0),
        ),
    ]
