# Generated by Django 3.2.5 on 2021-08-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_region'),
        ('patient', '0002_administeredtreatment_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayexamination',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_reported_to', to='accounts.staff'),
        ),
    ]
