# Generated by Django 3.2.5 on 2021-08-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_xrayexamination_reported_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xrayexamination',
            old_name='reported_by',
            new_name='requested_to',
        ),
    ]
