# Generated by Django 3.2.5 on 2021-08-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_region'),
        ('patient', '0004_rename_reported_by_xrayexamination_requested_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayexamination',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_to', to='accounts.staff'),
        ),
    ]
