# Generated by Django 3.2.5 on 2021-08-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_region'),
        ('patient', '0005_alter_xrayexamination_requested_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayexamination',
            name='finding_and_diagnosis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='xrayexamination',
            name='examination_requested',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='xrayexamination',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_requested_to', to='accounts.staff'),
        ),
    ]
