# Generated by Django 3.2.5 on 2021-08-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_num_waiting'),
        ('patient', '0006_auto_20210815_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasound',
            name='requested_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_requested_to', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_reported_by', to='accounts.staff'),
        ),
    ]
