# Generated by Django 3.2.5 on 2021-08-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_num_waiting'),
        ('patient', '0007_auto_20210816_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultrasound',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='xrayexamination',
            name='x_ray_report',
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_requested_to', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='ultrasound',
            name='ultra_sound_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='xrayexamination',
            name='x_ray_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
