# Generated by Django 3.2.5 on 2021-07-23 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_waiting_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptionist', models.BooleanField(default=False)),
                ('nurse', models.BooleanField(default=False)),
                ('triage', models.BooleanField(default=False)),
                ('physician', models.BooleanField(default=False)),
                ('radiologist', models.BooleanField(default=False)),
                ('lab_technician', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
