# Generated by Django 3.2.5 on 2021-08-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientwaitinglist',
            name='physician_speciality',
            field=models.CharField(default='oncology', max_length=50),
            preserve_default=False,
        ),
    ]
